const TYPE_PREFIX = '@HTT/HEADER/';
export const UNMOUNT  = `${TYPE_PREFIX}UNMOUNT`;
export const SET_MOFIFY_CHANGE_PASSWORD  = `${TYPE_PREFIX}SET_MOFIFY_CHANGE_PASSWORD`;
export const SET_OPEN_DIALOG_CHANGE_PASSWORD  = `${TYPE_PREFIX}SET_OPEN_DIALOG_CHANGE_PASSWORD`;
export const SET_SHOW_PASSWORD  = `${TYPE_PREFIX}SET_SHOW_PASSWORD`;
export const SET_SUBMIT_CHANGE_PASSWORD  = `${TYPE_PREFIX}SET_SUBMIT_CHANGE_PASSWORD`;
export const SET_OPEN_DIALOG_CHANGE_PASSWORD_SUCCESS  = `${TYPE_PREFIX}SET_OPEN_DIALOG_CHANGE_PASSWORD_SUCCESS`;
