import { NAME_REDUCER_T_LAYOUTS, KEY_TRANSLATE_T_LAYOUTS, PATH_TO_STORE_REDUX_T_LAYOUTS } from '../layouts';
import { PATH_TO_STORE_REDUX_DASHBOARD_APPS, SORT_SOURCE_NAME } from '../components';

export {
    NAME_REDUCER_T_LAYOUTS, KEY_TRANSLATE_T_LAYOUTS, PATH_TO_STORE_REDUX_T_LAYOUTS,
    PATH_TO_STORE_REDUX_DASHBOARD_APPS, SORT_SOURCE_NAME
}
