export const LOGOUT = '@DGS/AUTHENTICATION/LOGOUT';
export const LOGIN = '@DGS/AUTHENTICATION/LOGIN';
export const SET_ROUTERS = '@DGS/AUTHENTICATION/SET_ROUTERS';
export const REFRESH_TOKEN = '@DGS/AUTHENTICATION/REFRESH_TOKEN';
export const CHECK_TOKEN = '@DGS/AUTHENTICATION/CHECK_TOKEN';
export const SHOW_SIGNIN_EXP_TIME = '@DGS/AUTHENTICATION/SHOW-SIGNIN-EXP-TIME';
export const AUTH_REDUCER_NAME = 'authentication';
export const PATH_TO_STORE_AUTH = 'authentication';
