export const GET_TOKEN = '@DGS/AUTHENTICATION/GET_TOKEN';
export const LOGOUT = '@DGS/AUTHENTICATION/LOGOUT';
export const LOGIN = '@DGS/AUTHENTICATION/LOGIN';
export const CLEAR_AUTH = '@DGS/AUTHENTICATION/CLEAR_AUTH';
export const ERROR_MESSAGE = '@DGS/AUTHENTICATION/ERROR_MESSAGE';
export const SET_USER_INFO = '@DGS/AUTHENTICATION/SET_USER_INFO';
