export const GET_ONE = '@DGS/DATA_FETCH/GET_ONE';
export const GET_LIST = '@DGS/DATA_FETCH/GET_LIST';
export const GET_MANY = '@DGS/DATA_FETCH/GET_MANY';
export const GET_COUNT = '@DGS/DATA_FETCH/GET_COUNT';
export const GET_MANY_REFERENCE = '@DGS/DATA_FETCH/GET_MANY_REFERENCE';

export const CREATE = '@DGS/DATA_FETCH/CREATE';
export const CREATE_MANY = '@DGS/DATA_FETCH/CREATE_MANY';

export const UPDATE = '@DGS/DATA_FETCH/UPDATE';
export const UPDATE_MANY = '@DGS/DATA_FETCH/UPDATE_MANY';

export const DELETE = '@DGS/DATA_FETCH/DELETE';
export const DELETE_MANY = '@DGS/DATA_FETCH/DELETE_MANY';
