const TYPE_PREFIX = '@HTT/HEADER/';
export const UNMOUNT = `${TYPE_PREFIX}UNMOUNT`;
export const SET_OPEN_MENU_PROFILE = `${TYPE_PREFIX}SET_OPEN_MENU_PROFILE`;
export const SET_OPEN_MOBILE_MENU = `${TYPE_PREFIX}SET_OPEN_MOBILE_MENU`;
export const SET_OPEN_CONTACT_MENU = `${TYPE_PREFIX}SET_OPEN_CONTACT_MENU`;
export const SET_GET_DATA_FOR_READY = `${TYPE_PREFIX}SET_GET_DATA_FOR_READY`;
export const SET_BREAK_POINTS = `${TYPE_PREFIX}SET_BREAK_POINTS`;

// announcement
export const GET_DATA_DRAWER_ANNOUNCEMENT = `${TYPE_PREFIX}GET_DATA_DRAWER_ANNOUNCEMENT`;
export const CLICK_ITEM_ANNOUNCEMENT = `${TYPE_PREFIX}CLICK_ITEM_ANNOUNCEMENT`;
export const UPDATE_DATA_DRAWER_ANNOUNCEMENT = `${TYPE_PREFIX}UPDATE_DATA_DRAWER_ANNOUNCEMENT`;
export const OPEN_DRAWER_ANNOUNCEMENT = `${TYPE_PREFIX}OPEN_DRAWER_ANNOUNCEMENT`;
export const OPEN_DIALOG_DETAIL_ANNOUNCEMENT = `${TYPE_PREFIX}OPEN_DIALOG_DETAIL_ANNOUNCEMENT`;
export const SEARCH_KEY_WORD_ANNOUNCEMENT = `${TYPE_PREFIX}SEARCH_KEY_WORD_ANNOUNCEMENT`;
export const ACTION_SHOW_ANNOUNCEMENT = `${TYPE_PREFIX}ACTION_SHOW_ANNOUNCEMENT`;
export const ACTION_HIDE_ANNOUNCEMENT = `${TYPE_PREFIX}ACTION_HIDE_ANNOUNCEMENT`;
export const SET_OPEN_LEFT_MENU = `${TYPE_PREFIX}SET_OPEN_LEFT_MENU`;

// breadcrumbs
export const SET_CLICK_BREADCRUMBS_ITEM = `${TYPE_PREFIX}SET_CLICK_BREADCRUMBS_ITEM`;
export const SET_IS_VIEW_BREADCRUMBS = `${TYPE_PREFIX}SET_IS_VIEW_BREADCRUMBS`;
export const CREATE_BREADCRUMBS_HEADER = `${TYPE_PREFIX}CREATE_BREADCRUMBS_HEADER`;
export const UPDATE_BREADCRUMBS_HEADER = `${TYPE_PREFIX}UPDATE_BREADCRUMBS_HEADER`;
