import { NAME_REDUCER_T_LAYOUTS, KEY_TRANSLATE_T_LAYOUTS, PATH_TO_STORE_REDUX_T_LAYOUTS } from '../../../constants';

const NAME_REDUCER = 'dashboard_root';
const KEY_TRANSLATE = KEY_TRANSLATE_T_LAYOUTS;
const PATH_TO_STORE_REDUX = `core.resources.${NAME_REDUCER}.data`;
const POSTFIX_ID_REF_APP = '_APP';
export {
    NAME_REDUCER, KEY_TRANSLATE, PATH_TO_STORE_REDUX, POSTFIX_ID_REF_APP,
    NAME_REDUCER_T_LAYOUTS,
    KEY_TRANSLATE_T_LAYOUTS,
    PATH_TO_STORE_REDUX_T_LAYOUTS
}
