const TYPE_PREFIX = '@HTT/HEADER/';
export const UNMOUNT  = `${TYPE_PREFIX}UNMOUNT`;
export const SET_KEYBOARD_DASHBOARD_ROOT  = `${TYPE_PREFIX}SET_KEYBOARD_DASHBOARD_ROOT`;
export const SET_REF_CONTAINER_DASHBOARD_ROOT  = `${TYPE_PREFIX}SET_REF_CONTAINER_DASHBOARD_ROOT`;

