export const UNMOUNT  = '@HTT/UNMOUNT_CRON_TRIGGER';
export const GET_OPTION_NOTIFICATION  = '@HTT/GET_OPTION_NOTIFICATION';
export const SET_CLICK_OPTION_NOTIFICATION  = '@HTT/SET_CLICK_OPTION_NOTIFICATION';
export const SET_SUBCRIBE_NOTIFICATION  = '@HTT/SET_SUBCRIBE_NOTIFICATION';
export const SET_CHECKED_DISABLED_NOTIFICATION  = '@HTT/SET_CHECKED_DISABLED_NOTIFICATION';
export const SET_OPEN_MENU_OPTION_NOTIFICATION  = '@HTT/SET_OPEN_MENU_OPTION_NOTIFICATION';
