const TYPE_PREFIX = '@HTT/DASHBOARD-PROJECTS/';
export const UNMOUNT  = `${TYPE_PREFIX}UNMOUNT`;
export const SET_GET_DATA_FOR_READY_PROJECT  = `${TYPE_PREFIX}SET_GET_DATA_FOR_READY_PROJECT`;
export const SET_KEYBOARD_PROJECT  = `${TYPE_PREFIX}SET_KEYBOARD_PROJECT`;
export const SET_REF_CONTAINER_PROJECT  = `${TYPE_PREFIX}SET_REF_CONTAINER_PROJECT`;
export const SET_SEARCH_PROJECT  = `${TYPE_PREFIX}SET_SEARCH_PROJECT`;
export const SET_VIEW_PROJECT  = `${TYPE_PREFIX}SET_VIEW_PROJECT`;
export const SET_SORT_PROJECT  = `${TYPE_PREFIX}SET_SORT_PROJECT`;
export const SET_PAGE_PROJECT  = `${TYPE_PREFIX}SET_PAGE_PROJECT`;
export const SET_ROWS_PER_PAGE_PROJECT  = `${TYPE_PREFIX}SET_ROWS_PER_PAGE_PROJECT`;

export const SET_GET_DATA_FOR_READY_FUNCTION_TASKS  = `${TYPE_PREFIX}SET_GET_DATA_FOR_READY_FUNCTION_TASKS`;
export const SET_KEYBOARD_FUNCTION_TASKS  = `${TYPE_PREFIX}SET_KEYBOARD_FUNCTION_TASKS`;
export const SET_SEARCH_FUNCTION_TASKS  = `${TYPE_PREFIX}SET_SEARCH_FUNCTION_TASKS`;
export const SET_REFRESH_INSTANCES_FUNCTION_TASKS  = `${TYPE_PREFIX}SET_REFRESH_INSTANCES_FUNCTION_TASKS`;


export const SET_GET_DATA_FOR_READY_FUNCTION  = `${TYPE_PREFIX}SET_GET_DATA_FOR_READY_FUNCTION`;
export const SET_KEYBOARD_FUNCTION  = `${TYPE_PREFIX}SET_KEYBOARD_FUNCTION`;
export const SET_REF_CONTAINER_FUNCTION  = `${TYPE_PREFIX}SET_REF_CONTAINER_FUNCTION`;
export const SET_SEARCH_FUNCTION  = `${TYPE_PREFIX}SET_SEARCH_FUNCTION`;