const TYPE_PREFIX = '@DGS/UPLOAD-IMAGE/';
export const UNMOUNT = `${TYPE_PREFIX}UNMOUNT`;
export const SET_BREAKPOINT = `${TYPE_PREFIX}SET_BREAKPOINT`;

export const SET_OPEN_MENU_PROFILE = `${TYPE_PREFIX}SET_OPEN_MENU_PROFILE`;
export const SET_OPEN_MOBILE_MENU = `${TYPE_PREFIX}SET_OPEN_MOBILE_MENU`;
export const SET_OPEN_CONTACT_MENU = `${TYPE_PREFIX}SET_OPEN_CONTACT_MENU`;
export const SET_OPEN_LEFT_MENU = `${TYPE_PREFIX}SET_OPEN_LEFT_MENU`;
export const SET_DATA_READY = `${TYPE_PREFIX}SET_DATA_READY`;
export const SET_CLICK_LEFT_MENU_ITEM = `${TYPE_PREFIX}SET_CLICK_LEFT_MENU_ITEM`;
