const TYPE_PREFIX = '@DGS/LAYOUT-ROOT/';
export const UNMOUNT = `${TYPE_PREFIX}UNMOUNT`;
export const SET_BREAKPOINT = `${TYPE_PREFIX}SET_BREAKPOINT`;

export const SET_OPEN_MENU_PROFILE = `${TYPE_PREFIX}SET_OPEN_MENU_PROFILE`;
export const SET_OPEN_MOBILE_MENU = `${TYPE_PREFIX}SET_OPEN_MOBILE_MENU`;
export const SET_OPEN_CONTACT_MENU = `${TYPE_PREFIX}SET_OPEN_CONTACT_MENU`;
export const SET_OPEN_LEFT_MENU = `${TYPE_PREFIX}SET_OPEN_LEFT_MENU`;
export const SET_DATA_READY = `${TYPE_PREFIX}SET_DATA_READY`;
export const SET_CLICK_LEFT_MENU_ITEM = `${TYPE_PREFIX}SET_CLICK_LEFT_MENU_ITEM`;
export const SET_SEARCH_LEFT_MENU = `${TYPE_PREFIX}SET_SEARCH_LEFT_MENU`;
export const ADD_TREE_ITEM_BY_TREE_NODE = `${TYPE_PREFIX}ADD_TREE_ITEM_BY_TREE_NODE`;
export const CREATE_BREADCRUMBS_BY_TREE_NODE = `${TYPE_PREFIX}CREATE_BREADCRUMBS_BY_TREE_NODE`;
export const SET_DATA_TRAINING = `${TYPE_PREFIX}SET_DATA_TRAINING`;
export const SET_DATA_OPERATION = `${TYPE_PREFIX}SET_DATA_OPERATION`;
